- name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
  steps:
    - name: Set up Git repository
      uses: actions/checkout@1
    - name: Compile LaTeX document
  # You may pin to the exact commit or the version.
  # uses: dante-ev/latex-action@259e5ff953ad4d4616fbd09cc87a526ee5c4499a
  # uses: dante-ev/latex-action@v0.2.0
      uses: dante-ev/latex-action@master
  with:
    # The root LaTeX file to be compiled
    root_file: main.tex
    # The working directory for the latex compiler to be invoked
    # working_directory: # optional
    # LaTeX engine to be used
    # compiler: # optional, default is latexmk
    # Extra arguments to be passed to the latex compiler
    args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode # optional, default is -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
    # Install extra packages by apt-get
    # extra_system_packages: # optional
